apiVersion: v1
kind: Pod
metadata:
  name: pod-config-all
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: nginx-config
      # env:
      #   - name: course
      #     valueFrom:
      #       configMapKeyRef:
      #         name: nginx-config
      #         key: duration