kind: Pod
apiVersion: v1
metadata:
  name: pod-configs
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: nginx-config
      # env:
      #   - name: course
      #     valueFrom:
      #       configMapKeyRef:
      #         name: nginx-config
      #         key: course 
      #   - name: duration
      #     valueFrom:
      #       configMapKeyRef:
      #         name: nginx-config
      #         key: duration
      