---
apiVersion: v1
kind: Pod
metadata:
  name: pod-configs
spec:
  containers:
    envFrom:
      - configMapRef:
          name: nginx-config
        image: nginx
      - name: nginx
      # env:
      #   - name: course
      #     valueFrom:
      #       configMapKeyRef:
      #         name: nginx-config
      #         key: duration