---
apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
    - env:
        - name: course
          valueFrom:
            configMapKeyRef:
              key: course
              name: nginx-config
        - name: duration
          valueFrom:
            configMapKeyRef:
              key: duration
              name: nginx-config
      image: nginx
      name: nginx